---
- name: Deploy infrastructure with Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Check docker
      apt:
        name: docker.io
        state: present

    - name: Check docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Create app dir
      file:
        path: ./app
        state: directory

    - name: Copy docker-compose.yml 
      copy:
        src: ./docker-compose.yml
        dest: ./app/docker-compose.yml

    - name: Copy nginx.conf 
      copy:
        src: ./nginx.conf
        dest: ./app/nginx.conf

    - name: Start Docker containers
      command: docker-compose up -d
      args:
        chdir: ./app
